Xilinx/torch-mlir

lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp
python/torch_mlir_e2e_test/test_suite/slice_like.py

related upstream PR: https://github.com/llvm/torch-mlir/pull/1970

SliceCopyMax_Module: Fix crash

---

python/torch_mlir/compiler_utils.py

From sources of `failed to legalize operation 'torch.constant.int'`
- torch.ops.aten.cumsum
With the first commit `python ./model.py --fxtype tosa --modeltype bf16 --checkpoint xlm-roberta-base --modelname XLMRobertaModel` then fails with:
```
error: "<eval_with_key>.2":23:20: unsupported by backend contract: Unimplemented operator 'aten.scalar_tensor'
note: "<eval_with_key>.2":23:20: see current operation: %246 = "torch.operator"(%0, %3, %0, %221, %4) {name = "aten.scalar_tensor"} : (!torch.int, !torch.int, !torch.int, !torch.Device, !torch.none) -> !torch.tensor
```

add decomposes to model to fxgraph

---

python/CMakeLists.txt
python/torch_mlir/__init__.py
python/torch_mlir/compiler_utils.py
python/torch_mlir/fx_minifier.py
python/torch_mlir/repro.py

- Extract a common model_to_fxgraph() function
- Add a copy of https://github.com/pytorch/pytorch/blob/main/torch/_functorch/fx_minifier.py with fixes to how tuples are handled (will open an upstream PR)
- Add python/torch_mlir/repro.py to reduce torch models while keeping the same error out of `torch_mlir.compile(make_fx(model))`
Example output:
```
Strategy: Eliminate dead code (G: 2) (3 nodes, 1 inputs)
FAIL: Eliminate dead code
Strategy: Remove unused inputs (G: 2) (3 nodes, 1 inputs)
FAIL: Remove unused inputs
Strategy: Truncate suffix (G: 2) (3 nodes, 1 inputs)
FAIL: Truncate suffix
Strategy: Delta Debugging (G: 2) (3 nodes, 1 inputs)
FAIL: Delta Debugging
Trying granularity 1
Strategy: Truncate suffix (G: 1) (3 nodes, 1 inputs)
FAIL: Truncate suffix
Strategy: Delta Debugging (G: 1) …
```

Add reproduce() function

---

lib/Conversion/TorchToTosa/TorchToTosa.cpp

This redirects the error message to talk about the actual problematic ops like cumsum.

Ignore constants in the legality error

---

.github/workflows/buildRelease.yml

To allow users on Ubuntu 22.04 to use the package.

.github/workflows/buildRelease.yml: Also build packages for python 3.10

---

e2e_testing/xfail_sets.py
include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py
python/torch_mlir_e2e_test/test_suite/basic.py

The aten.broadcast_to op both does broadcasting but can also increase the rank by adding dimensions with size 1.
The torch->tosa lowering only handles broadcast_to that are not increasing the rank. To also help other backends, I added a canonicalizer for broadcast_to that splits into into a reshape and a non-rank changing broadcast_to.

lib/Dialect/Torch/IR/TorchOps.cpp: Canonicalize rank changing broadcast_to into reshape + broadcast_to

---

python/torch_mlir/repro.py

To avoid error about "leave tensor requires grad"

Use torch.nograd on reproduce()

---

python/CMakeLists.txt
python/torch_mlir/_version.py
python/torch_mlir/dynamo.py
python/torch_mlir_e2e_test/test_suite/__init__.py

It's not safe to compare against `"2.0.1+cpu"` because torch by default gets installed inteh `+cu117` version (i.e. CUDA).

Fix version comparison against stable

---

python/torch_mlir/__init__.py
python/torch_mlir/compiler_utils.py
python/torch_mlir/repro.py

Since we added that flag to torch_mlir.compile(), we can remove some duplicate code.

do: Use use_make_fx flag on compile()

---

e2e_testing/xfail_sets.py
lib/Conversion/TorchToTosa/TorchToTosa.cpp

It's actually fine to not check the rank of the indices, because the conversion anyways flattens the index tensor to be `(1, numElements)` before applying `tosa::gather`, and then anyways reshapes the output tensor to the output shape of the `aten.embedding`.

TorchToTosa: aten.embedding: Allow indices with any rank

---

e2e_testing/xfail_sets.py
python/torch_mlir/dynamo.py

There are existing test cases in python/torch_mlir_e2e_test/test_suite/index_select.py, but they require #67 to pass.

python/torch_mlir/dynamo.py: Decompose index_select

---

lib/Dialect/Torch/IR/TorchOps.cpp
test/Dialect/Torch/canonicalize.mlir

Fix bug introduced by #37. It's not safe to fold the slice away if the step is not 1.

Fix SliceOp::fold to check step (introduced by #37)

---

python/torch_mlir/__init__.py
python/torch_mlir_e2e_test/configs/tosa_backend.py

This backports #66 but without adding the end2end test flow (which needs an LLVM bump to not crash one specific test case in the tosa fold),
and without a decomposition table in make_fx (this requires a newer torch_mlir version, which has the decomposition table in dynamo.py).
This allows us to internally already use the use_make_fx flag in our testing in a forward compatible way.
In parallel, we are upstreaming this new flag into torch-mlir.

Backport use_make_fx from https://github.com/Xilinx/torch-mlir/pull/66

---

lib/Conversion/TorchToTosa/TorchToTosa.cpp

There is no need to create a `tosa.cast` operation if types are the same.

TorchToTosa: optimize aten.fill.Scalar legalization.

---

e2e_testing/xfail_sets.py
lib/Conversion/TorchToTosa/TorchToTosa.cpp
python/torch_mlir_e2e_test/test_suite/basic.py

Unfortunately, the legalization works only for static `repeats` and known `output_size`.

TorchToTosa: Legalize aten.repeat_interleave operation.

---

e2e_testing/xfail_sets.py
lib/Dialect/Torch/Transforms/LowerToBackendContract.cpp
lib/Dialect/Torch/Transforms/RecomposeComplexOps.cpp
python/torch_mlir_e2e_test/test_suite/basic.py

This is a different approach where I will add the output_size to repeat_interleave if the repeats argument is produced by broadcast(fill.Scalar(...)).
Then the existing TOSA lowering works.

Derive output_size of repeat_interleave when inputs are broadcast(fill(x))

---

lib/Dialect/Torch/IR/TorchOps.cpp
test/Dialect/Torch/ops.mlir

I noticed that if the following was printed:
```
%int5 = torch.constant.int 5 {test = "value"}
```
The assembly parser would fail. That is because the custom parser expected the dictionary in another order. The fix here is to correct it.
The format follows what the other constant operations expected which is `$value attr-dict`

[FXML-2294] Fix Constant Int Assembly Parser

---

python/torch_mlir/__init__.py
python/torch_mlir/compiler_utils.py

Previously we used `iree-torch` which is discontinued and hard to install. Replace this with standard iree code.

Fix execution via iree

---

test/CAPI/CMakeLists.txt

I saw test failing when FileCheck wasn't already build

test/CAPI/CMakeLists.txt: Depend on FileCheck

---

e2e_testing/xfail_sets.py
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp

I also needed to update the LLVM branch to be in sync with [xilinx/llvm-project feature/backport_ea1_ops](https://github.com/Xilinx/torch-mlir/commit/f496fd488f50c1c056e583c7bb5c10ef2de0c9fb)
because they contain fix for a crash in TOSA folds.

torch.aten.max pool2d with indices

---

e2e_testing/xfail_sets.py
lib/Dialect/Torch/Transforms/DecomposeComplexOps.cpp

More tests passing for make_fx flow

DecomposeComplexOps: Use static shape if available

---

pytorch-requirements.txt
torchvision-requirements.txt

In case the version of pytorch and torchvision we refer to is deleted on pytorch.org, we should derive it from our release page.

Add additional source for pytorch+torchvision whls

---

include/torch-mlir/Dialect/Torch/IR/GeneratedTorchOps.td
lib/Dialect/Torch/IR/TorchOps.cpp
python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py

Unused allocations of tensors are currently not optimized away properly. Implement a folder for this specific op to enable getting rid of them, while discussing a proper solution to optimize unused memory allocations.

Implement folder for unused empty.memory_formats

---

lib/Conversion/TorchToTosa/TorchToTosa.cpp

Simplify lowering. 
from:
aten.le -> tosa.gt + tosa.ne 
to:
aten.le -> tosa.ge (with swapped ops)

feat: lower to TOSA AtenLe as tosa.greater_equal with swapped ops

---

e2e_testing/main.py
e2e_testing/xfail_sets.py
test-requirements.txt

`mpmath 1.4.0` changes some import locations breaking `torch`. Changing to `1.3.0` to avoid breaking on `python 3.11`
You can see the failure in our CI pipeline here: https://github.com/Xilinx/torch-mlir/actions/runs/8064232110
Backported from https://github.com/llvm/torch-mlir/pull/2946

[ci] Fix mpmath 1.4.0 error by forcing 1.3.0
